name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          build: npm run build
          start: npm run dev:all
      - name: Create artifact directories
        if: always()
        run: |
          mkdir -p cypress/videos
          mkdir -p cypress/screenshots
          mkdir -p cypress/reports
      - name: Cypress Test - Video Artifacts
        uses: actions/upload-artifact@v4
        if: always() # Instruct a step to always run, regardless of whether or not the steps before it pass. Please see https://github.com/cypress-io/github-action/issues/33
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Cypress Test - Screenshot Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Cypress Test - Mochawesome Reports Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-mochawesome-reports
          path: cypress/reports
